BraimServer_rails/config/routes.rb
Rails.application.routes.draw do
  resources :player_entries

  resources :braim_sessions do 
    get 'raw' , on: :member
    get 'affectiv', on: :member
  end

  resources :epoc_entries

  resources :songs

  resources :albums

  resources :bands

  devise_for :users

  root 'welcome#index'
  get 'about' =>  "welcome#about"
  get 'setup' => "welcome#setup"

  get 'ping' => 'welcome#ping'

  get 'dashboard' => 'dashboard#index'
  mount API => '/'
  mount GrapeSwaggerRails::Engine => '/api_doc'

end

BraimServer_rails/app/models/band.rb
class Band
  include Mongoid::Document
  field :name, type: String
  field :genre, type: String
  field :biography, type: String

  has_many :albums
end

BraimServer_rails/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: [:show, :edit, :update, :destroy]

  # GET /bands
  # GET /bands.json
  def index
    @bands = Band.all
  end

  # GET /bands/1
  # GET /bands/1.json
  def show
  end

  # GET /bands/new
  def new
    @band = Band.new
  end

  # GET /bands/1/edit
  def edit
  end

  # POST /bands
  # POST /bands.json
  def create
    @band = Band.new(band_params)

    respond_to do |format|
      if @band.save
        format.html { redirect_to @band, notice: 'Band was successfully created.' }
        format.json { render :show, status: :created, location: @band }
      else
        format.html { render :new }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bands/1
  # PATCH/PUT /bands/1.json
  def update
    respond_to do |format|
      if @band.update(band_params)
        format.html { redirect_to @band, notice: 'Band was successfully updated.' }
        format.json { render :show, status: :ok, location: @band }
      else
        format.html { render :edit }
        format.json { render json: @band.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bands/1
  # DELETE /bands/1.json
  def destroy
    @band.destroy
    respond_to do |format|
      format.html { redirect_to bands_url, notice: 'Band was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band
      @band = Band.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def band_params
      params.require(:band).permit(:name, :genre, :biography)
    end
end

BraimServer_rails/app/helpers/bands_helper.rb
module BandsHelper
end

BraimServer_rails/app/views/bands/_form.html.haml
= simple_form_for(@band) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :genre
    = f.input :biography

  .form-actions
    = f.button :submit

BraimServer_rails/app/views/bands/edit.html.haml
%h1 Editing band

= render 'form'

= link_to 'Show', @band
\|
= link_to 'Back', bands_path

BraimServer_rails/app/views/bands/index.html.haml
%h1 Listing bands

%table
  %tr
    %th Name
    %th Genre
    %th Biography
    %th
    %th
    %th

  - @bands.each do |band|
    %tr
      %td= band.name
      %td= band.genre
      %td= band.biography
      %td= link_to 'Show', band
      %td= link_to 'Edit', edit_band_path(band)
      %td= link_to 'Destroy', band, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Band', new_band_path

BraimServer_rails/app/views/bands/new.html.haml
%h1 New band

= render 'form'

= link_to 'Back', bands_path

BraimServer_rails/app/views/bands/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @band.name
%p
  %b Genre:
  = @band.genre
%p
  %b Biography:
  = @band.biography

= link_to 'Edit', edit_band_path(@band)
\|
= link_to 'Back', bands_path