BraimServer_rails/config/routes.rb
Rails.application.routes.draw do
  resources :player_entries

  resources :braim_sessions do 
    get 'raw' , on: :member
    get 'affectiv', on: :member
  end

  resources :epoc_entries

  resources :songs

  resources :albums

  resources :bands

  devise_for :users

  root 'welcome#index'
  get 'about' =>  "welcome#about"
  get 'setup' => "welcome#setup"

  get 'ping' => 'welcome#ping'

  get 'dashboard' => 'dashboard#index'
  mount API => '/'
  mount GrapeSwaggerRails::Engine => '/api_doc'

end

BraimServer_rails/app/models/song.rb
class Song
  include Mongoid::Document
  mount_uploader :file, FileUploader

  field :name, type: String
  field :duration, type: Integer
  field :file, type: String
  
  belongs_to :album
end

BraimServer_rails/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:name, :duration , :file)
    end
end

BraimServer_rails/app/helpers/songs_helper.rb
module SongsHelper
end

BraimServer_rails/app/views/songs/_form.html.haml
= simple_form_for(@song) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :duration
    = f.input :file, type: :file

  .form-actions
    = f.button :submit

BraimServer_rails/app/views/songs/edit.html.haml
%h1 Editing song

= render 'form'

= link_to 'Show', @song
\|
= link_to 'Back', songs_path

BraimServer_rails/app/views/songs/index.html.haml
%h1 Listing songs

%table
  %tr
    %th Name
    %th Duration
    %th
    %th
    %th

  - @songs.each do |song|
    %tr
      %td= song.name
      %td= song.duration
      %td= link_to 'Show', song
      %td= link_to 'Edit', edit_song_path(song)
      %td= link_to 'Destroy', song, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Song', new_song_path

BraimServer_rails/app/views/songs/new.html.haml
%h1 New song

= render 'form'

= link_to 'Back', songs_path

BraimServer_rails/app/views/songs/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @song.name
%p
  %b Duration:
  = @song.duration
%p
  %b File
  =link_to @song.file_url, @song.file_url

= link_to 'Edit', edit_song_path(@song)
\|
= link_to 'Back', songs_path