BraimServer_rails/config/routes.rb
Rails.application.routes.draw do
  resources :player_entries

  resources :braim_sessions do 
    get 'raw' , on: :member
    get 'affectiv', on: :member
  end

  resources :epoc_entries

  resources :songs

  resources :albums

  resources :bands

  devise_for :users

  root 'welcome#index'
  get 'about' =>  "welcome#about"
  get 'setup' => "welcome#setup"

  get 'ping' => 'welcome#ping'

  get 'dashboard' => 'dashboard#index'
  mount API => '/'
  mount GrapeSwaggerRails::Engine => '/api_doc'

end

BraimServer_rails/app/models/player_entry.rb
class PlayerEntry
  include Mongoid::Document
  belongs_to :braim_session

  field :user_id, type: BSON::ObjectId
  field :song_id, type: BSON::ObjectId
  field :timestamp, type: Float
  field :action , type: Symbol

  def player_state
    action == :play ? 1 : 0
  end
  def song
    Song.find(song_id)
  end
end

BraimServer_rails/app/controllers/player_entries_controller.rb
class PlayerEntriesController < ApplicationController
  before_action :set_player_entry, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @player_entries = PlayerEntry.all
    respond_with(@player_entries)
  end

  def show
    respond_with(@player_entry)
  end

  def new
    @player_entry = PlayerEntry.new
    respond_with(@player_entry)
  end

  def edit
  end

  def create
    @player_entry = PlayerEntry.new(player_entry_params)
    @player_entry.save
    respond_with(@player_entry)
  end

  def update
    @player_entry.update(player_entry_params)
    respond_with(@player_entry)
  end

  def destroy
    @player_entry.destroy
    respond_with(@player_entry)
  end

  private
    def set_player_entry
      @player_entry = PlayerEntry.find(params[:id])
    end

    def player_entry_params
      params[:player_entry]
    end
end

BraimServer_rails/app/helpers/player_entries_helper.rb
module PlayerEntriesHelper
end

BraimServer_rails/app/views/player_entries/_form.html.haml
= simple_form_for(@player_entry) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

BraimServer_rails/app/views/player_entries/edit.html.haml
%h1 Editing player_entry

= render 'form'

= link_to 'Show', @player_entry
\|
= link_to 'Back', player_entries_path

BraimServer_rails/app/views/player_entries/index.html.haml
%h1 Listing player_entries

%table
  %tr
    %th
    %th
    %th

  - @player_entries.each do |player_entry|
    %tr
      %td= link_to 'Show', player_entry
      %td= link_to 'Edit', edit_player_entry_path(player_entry)
      %td= link_to 'Destroy', player_entry, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Player entry', new_player_entry_path

BraimServer_rails/app/views/player_entries/new.html.haml
%h1 New player_entry

= render 'form'

= link_to 'Back', player_entries_path

BraimServer_rails/app/views/player_entries/show.html.haml
%p#notice= notice

%p
  Timestamp:
  =@player_entry.timestamp
%p
  Song ID:
  =@player_entry.song_id
%p
  Action
  =@player_entry.action
%p
  user:
  =@player_entry.emo_session.user.username
%p
  State:
  =@player_entry.player_state

= link_to 'Edit', edit_player_entry_path(@player_entry)
\|
= link_to 'Back', player_entries_path