BraimServer_rails/config/routes.rb
Rails.application.routes.draw do
  resources :player_entries

  resources :braim_sessions do 
    get 'raw' , on: :member
    get 'affectiv', on: :member
  end

  resources :epoc_entries

  resources :songs

  resources :albums

  resources :bands

  devise_for :users

  root 'welcome#index'
  get 'about' =>  "welcome#about"
  get 'setup' => "welcome#setup"

  get 'ping' => 'welcome#ping'

  get 'dashboard' => 'dashboard#index'
  mount API => '/'
  mount GrapeSwaggerRails::Engine => '/api_doc'

end

BraimServer_rails/app/models/braim_session.rb
class BraimSession
  include Mongoid::Document
  before_create :set_time

  has_many :epoc_entries
  has_many :player_entries
  belongs_to :user

#------------------ MODEL ATTRIBUTES ---------------------#

  field :start_at , type: Float

#------------------ INSTANCE METHODS ---------------------#

  def date
    Time.at(start_at).to_formatted_s(:long)
  end
  
  protected

  def set_time
    self.start_at = Time.now
  end

end

BraimServer_rails/app/controllers/braim_sessions_controller.rb
class BraimSessionsController < ApplicationController
  before_action :set_braim_session, only: [:show, :edit, :update, :destroy , :raw, :affectiv]

  respond_to :html

  def index
    @braim_sessions = BraimSession.all
    respond_with(@braim_sessions)
  end

  def show
    respond_with(@braim_session)
  end

  def raw
    @epoc_entries = @braim_session.epoc_entries
    @player_entries = @braim_session.player_entries 
    @data_node_0 = @epoc_entries.map {|entry| [entry.timestamp.to_i,entry.nodes[0]]}
    @data_node_1 = @epoc_entries.map {|entry| [entry.timestamp.to_f,entry.nodes[1]]}
    @data_node_2 = @epoc_entries.map {|entry| [entry.timestamp.to_f,entry.nodes[2]]}
    @data_node_3 = @epoc_entries.map {|entry| [entry.timestamp.to_f,entry.nodes[3]]}
    @data_node_4 = @epoc_entries.map {|entry| [entry.timestamp.to_f,entry.nodes[4]]}
    @data_node_5 = @epoc_entries.map {|entry| [entry.timestamp.to_f,entry.nodes[5]]}
    @data_node_6 = @epoc_entries.map {|entry| [entry.timestamp.to_f,entry.nodes[6]]}
    @data_node_7 = @epoc_entries.map {|entry| [entry.timestamp.to_f,entry.nodes[7]]}
    @data_node_8 = @epoc_entries.map {|entry| [entry.timestamp.to_f,entry.nodes[8]]}
    @data_node_9 = @epoc_entries.map {|entry| [entry.timestamp.to_f,entry.nodes[9]]}
    @data_node_10 = @epoc_entries.map {|entry| [entry.timestamp.to_f,entry.nodes[10]]}
    @data_node_11 = @epoc_entries.map {|entry| [entry.timestamp.to_f,entry.nodes[11]]}
    @data_node_12 = @epoc_entries.map {|entry| [entry.timestamp.to_f,entry.nodes[12]]}
    @data_node_13 = @epoc_entries.map {|entry| [entry.timestamp.to_f,entry.nodes[13]]}
    @player_timeline = @player_entries.map {|entry| [entry.timestamp.to_f,entry.player_state]}
    render :show
  end

  def affectiv
    @epoc_entries = @braim_session.epoc_entries
    @player_entries = @braim_session.player_entries 
    @data_excitement = @epoc_entries.map {|entry| [entry.timestamp.to_f,entry.excitement.to_f]}
    @data_frustration = @epoc_entries.map {|entry| [entry.timestamp.to_f,entry.frustration.to_f]}
    @data_meditation = @epoc_entries.map {|entry| [entry.timestamp.to_f,entry.meditation.to_f]}
    @data_engagement = @epoc_entries.map {|entry| [entry.timestamp.to_f,entry.engagement.to_f]}
    @player_timeline = @player_entries.map {|entry| [entry.timestamp.to_f,entry.player_state]}
    render :show
  end

  def new
    @braim_session = BraimSession.new
    respond_with(@braim_session)
  end

  def edit
  end

  def create
    @braim_session = BraimSession.new(braim_session_params)
    @braim_session.save
    respond_with(@braim_session)
  end

  def update
    @braim_session.update(braim_session_params)
    respond_with(@braim_session)
  end

  def destroy
    @braim_session.destroy
    respond_with(@braim_session)
  end

  private
    def set_braim_session
      @braim_session = BraimSession.find(params[:id])
    end

    def braim_session_params
      params[:braim_session]
    end
end

BraimServer_rails/app/views/braim_sessions/_af_chart.html.erb
<script type="text/javascript">
  $(function () {
    Highcharts.setOptions({
      global: {
        timezoneOffset: 5*60
      }
    });
    $('#stock').highcharts('StockChart', {
      rangeSelector : {
          selected : 1
      },

      title : {
          text : "<%=@braim_session.user.username%> session at: <%=@braim_session.date%>"
      },
      chart : {
        height: 500,
      },
      legend: { enabled: true},
      rangeSelector: {
        selected: 0,
        buttons: [{
          type: 'second',
          count: 10,
          text: '10s'
        },{
          type: 'second',
          count: 60,
          text: '1m'
        },{
          type: 'minute',
          count: 10,
          text: '10m'
        },{
          type: 'all',
          text: 'All'
        }],
        inputDateFormat: '%H:%M:%S.%L',
        inputEditDateFormat: '%H:%M:%S.%L',
        // Custom parser to parse the %H:%M:%S.%L format
        inputDateParser: function (value) {
            value = value.split(/[:\.]/);
            return Date.UTC(
                1970,
                0,
                1,
                parseInt(value[0], 10),
                parseInt(value[1], 10),
                parseInt(value[2], 10),
                parseInt(value[3], 10)
            );
        }
      },
      xAxis:{
        tickPixelInterval: 200,
        dateTimeLabelFormats:{
          millisecond: '%H:%M:%S'
        },
        plotBands:[
          <%@player_entries.each_with_index do|entry,i|%>
            <% if entry.action == :play%>
              {
                from: (new Date(<%=entry.timestamp%>)),
                to: (new Date(<%=@player_entries[i+1] ? @player_entries[i+1].timestamp : @epoc_entries[-1].timestamp%>)),
                color: "rgba(<%=rand(255)%>,<%=rand(255)%>,<%=rand(255)%>,0.1)",
                label: {
                  text: "<%=entry.song.name%>",
                  align: "center",
                  verticalAlign: "top"
                },
                zIndex: 0
              },
            <%end%>
          <%end%>
        ],

      },
      tooltip:{
        dateTimeLabelFormats: {
          millisecond:"%A - %b %e, %H:%M:%S.%L",
          second:"%A, %b %e, %H:%M:%S",
        }
      },
      navigator: {
        xAxis:{
          dateTimeLabelFormats:{
            millisecond: '%H:%M:%S.%L'
          }
        }
        //series: {
        //  data: <%=@player_timeline%>,
        //  type: 'line'
        //}
      },
      series : [{
        name : 'Excitement',
        data : <%=@data_excitement%>,
      },{
        name : 'Meditation',
        data : <%=@data_meditation%>,
      },{
        name : 'Engagement',
        data : <%=@data_engagement%>,
      },{
        name : 'Frustration',
        data : <%=@data_frustration%>,
      }]
    });
  });

</script>

BraimServer_rails/app/views/braim_sessions/_form.html.haml
= simple_form_for(@braim_session) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

BraimServer_rails/app/views/braim_sessions/_raw_chart.html.erb
<script type="text/javascript">
  $(function () {
    Highcharts.setOptions({
      global: {
        timezoneOffset: 5*60
      }
    });
    $('#stock').highcharts('StockChart', {
        rangeSelector : {
            selected : 1
        },

        title : {
            text : "<%=@braim_session.user.username%> session at: <%=@braim_session.date%>"
        },
        chart : {
          height: 500,
        },
        legend: { enabled: true},
        rangeSelector: {
          selected: 0,
          buttons: [{
            type: 'second',
            count: 10,
            text: '10s'
          },{
            type: 'second',
            count: 60,
            text: '1m'
          },{
            type: 'minute',
            count: 10,
            text: '10m'
          },{
            type: 'all',
            text: 'All'
          }],
          inputDateFormat: '%H:%M:%S.%L',
          inputEditDateFormat: '%H:%M:%S.%L',
          // Custom parser to parse the %H:%M:%S.%L format
          inputDateParser: function (value) {
              value = value.split(/[:\.]/);
              return Date.UTC(
                  1970,
                  0,
                  1,
                  parseInt(value[0], 10),
                  parseInt(value[1], 10),
                  parseInt(value[2], 10),
                  parseInt(value[3], 10)
              );
          }
        },
        xAxis:{
          tickPixelInterval: 200,
          dateTimeLabelFormats:{
            millisecond: '%H:%M:%S'
          },plotBands:[
            <%@player_entries.each_with_index do|entry,i|%>
              <% if entry.action == :play%>
                {
                  from: (new Date(<%=entry.timestamp%>)),
                  to: (new Date(<%=@player_entries[i+1] ? @player_entries[i+1].timestamp : @epoc_entries[-1].timestamp%>)),
                  color: "rgba(<%=rand(255)%>,<%=rand(255)%>,<%=rand(255)%>,0.1)",
                  label: {
                    text: "<%=entry.song.name%>",
                    align: "center",
                    verticalAlign: "top"
                  },
                  zIndex: 0
                },
              <%end%>
            <%end%>
          ],
        },
        tooltip:{
          dateTimeLabelFormats: {
            millisecond:"%A - %b %e, %H:%M:%S.%L",
            second:"%A, %b %e, %H:%M:%S",
          }
        },
        navigator: {
          xAxis:{
            dateTimeLabelFormats:{
              millisecond: '%H:%M:%S.%L'
            }
          },
          //series: {
          //  data: <%=@player_timeline%>,
          //  type: 'line'
          //}
        },
        series : [{
          name : 'Node 0',
          data : <%=@data_node_0%>,
        },{
          name : 'Node 1',
          data : <%=@data_node_1%>,
        },{
          name : 'Node 2',
          data : <%=@data_node_2%>,
        },{
          name : 'Node 3',
          data : <%=@data_node_3%>,
        },{
          name : 'Node 4',
          data : <%=@data_node_4%>,
        },{
          name : 'Node 5',
          data : <%=@data_node_5%>,
        },{
          name : 'Node 6',
          data : <%=@data_node_6%>,
        },{
          name : 'Node 7',
          data : <%=@data_node_7%>,
        },{
          name : 'Node 8',
          data : <%=@data_node_8%>,
        },{
          name : 'Node 9',
          data : <%=@data_node_9%>,
        },{
          name : 'Node 10',
          data : <%=@data_node_10%>,
        },{
          name : 'Node 11',
          data : <%=@data_node_11%>,
        },{
          name : 'Node 12',
          data : <%=@data_node_12%>,
        },{
          name : 'Node 13',
          data : <%=@data_node_13%>,
        }]
      });

  });
</script>

BraimServer_rails/app/views/braim_sessions/edit.html.haml
%h1 Editing session

= render 'form'

= link_to 'Show', @braim_session
\|
= link_to 'Back', braim_sessions_path

BraimServer_rails/app/views/braim_sessions/index.html.haml
%h1 Listing Braim sessions

%table
  %tr
    %th
    %th
    %th

  - @braim_sessions.each do |braim_session|
    %tr
      %td= link_to 'Show', braim_session
      %td= link_to 'Edit', edit_braim_session_path(braim_session)
      %td= link_to 'Destroy', braim_session, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Braim session', new_braim_session_path

BraimServer_rails/app/views/braim_sessions/new.html.haml
%h1 New braim session

= render 'form'

= link_to 'Back', braim_sessions_path

BraimServer_rails/app/views/braim_sessions/show.html.haml
%p#notice= notice
.text-center
  =link_to "EPOC Affectiv data", affectiv_braim_session_path(@braim_session), id: "button_nodes" ,class: "btn btn-#{params[:action] == 'affectiv' ? 'primary' : 'default'}"

  =link_to "EPOC Raw data", raw_braim_session_path(@braim_session), id: "button_nodes" ,class: "btn btn-#{params[:action] == 'raw' ? 'primary' : 'default'}"

#stock
=render "raw_chart", locals: {entries: @entries} if params[:action] == "raw"
=render "af_chart", locals: {entries: @entries} if params[:action] == "affectiv"

= link_to 'Edit', edit_braim_session_path(@braim_session)
\|
= link_to 'Back', braim_sessions_path